---
functional:
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
implicit:
 - Пользователь должен иметь возможность пользоваться сайтом без необходимости перезагрузки страниц благодаря одностраничному приложению (SPA)
 - Сайт должен сохранять содержимое корзины пользователя в сессии браузера, чтобы корзина оставалась доступной при закрытии сайта
 - Пользователь должен иметь возможность добавлять товары в корзину и продолжать выбирать другие товары в каталоге без прерываний
